---
# Always run including in check mode
- name: system packages | install selinux utilities
  become: true
  package:
    name:
      - libselinux-python
      - libsemanage-python
      - policycoreutils-python
    state: present
  when: selinux_enabled
