---
# tasks file for roles/selinux-utils

# NOTE: The Ansible variable `ansible_selinux.status == "enabled"` should
# autodetect SELinux, but may give a misleading result if a dependency is
# missing: https://github.com/ansible/ansible/issues/16612
# so use getenforce instead
- name: Selinux | check exists
  ansible.builtin.stat:
    path: /usr/sbin/getenforce
  register: selinux_getenforce_st
  check_mode: false

- name: Selinux | check enabled
  become: true
  ansible.builtin.command: /usr/sbin/getenforce
  register: selinux_getenforce
  check_mode: false
  changed_when: false
  when: selinux_getenforce_st.stat.exists

- name: System packages | set selinux variable
  ansible.builtin.set_fact:
    selinux_enabled: >-
      {{ selinux_getenforce_st.stat.exists and
         selinux_getenforce.stdout != 'Disabled' }}

- name: System packages | install selinux utilities
  become: true
  ansible.builtin.package:
    name:
      - libselinux-python
      - libsemanage-python
      - policycoreutils-python
    state: present
  when: selinux_enabled and ansible_facts['distribution_major_version'] == "7"

- name: System packages | install selinux utilities
  become: true
  ansible.builtin.package:
    name:
      - python3-libselinux
      - python3-libsemanage
      - policycoreutils-python-utils
    state: present
  when: selinux_enabled and ansible_facts['distribution_major_version'] == "8"
