---
# tasks file for roles/selinux-utils

# NOTE: The Ansible variable `ansible_selinux.status == "enabled"` should
# autodetect SELinux, but may give a misleading result if a dependency is
# missing: https://github.com/ansible/ansible/issues/16612
# so use getenforce instead

- import_tasks: redhat.yaml
  when: ansible_os_family | lower == 'redhat'

- import_tasks: debian.yaml
  when: ansible_os_family | lower == 'debian'

