---
# Always run including in check mode
- name: system packages | install selinux utilities
  become: true
  package:
    name:
      - libselinux-python
      - libsemanage-python
      - policycoreutils-python
    state: present
  when: selinux_enabled and ansible_facts['distribution_major_version'] == "7"

- name: system packages | install selinux utilities
  become: true
  package:
    name:
      - python3-libselinux
      - python3-libsemanage
      - policycoreutils-python-utils
    state: present
  when: selinux_enabled and ansible_facts['distribution_major_version'] == "8"
